import './style.css';

const markets = [
  { id:'h100', name:'H100 Compute', subtitle:'High-performance training', supply:'12,480', price:'$2.50', change:'+3.2%', tone:'mint', icon:'▣', points:'0,27 15,23 29,25 45,17 59,19 75,10 91,13 107,6 122,12 138,3 153,7 169,0' },
  { id:'a100', name:'A100 Compute', subtitle:'Reliable, versatile compute', supply:'18,920', price:'$1.20', change:'+1.8%', tone:'blue', icon:'▣', points:'0,29 15,28 30,25 44,27 58,17 72,21 87,13 101,15 116,6 131,11 147,3 169,5' },
  { id:'inference', name:'Inference Credits', subtitle:'Optimized for AI inference', supply:'11,400', price:'$0.35', change:'+4.6%', tone:'violet', icon:'▤', points:'0,30 14,24 29,26 43,19 57,21 72,12 85,15 100,9 114,12 129,4 144,7 157,2 169,4' }
];
const icons={arrow:'↗', cube:'⬡', globe:'◎', layers:'◈'};
const state={wallet:null,connecting:false};
const route=()=>location.pathname.replace(/\/$/,'')||'/';
const link=(path,label,cls='')=>`<a href="${path}" class="${cls}">${label}</a>`;
const walletLabel=()=>state.wallet?`${state.wallet.slice(0,6)}…${state.wallet.slice(-4)}`:'Connect wallet';
function header(){let p=route();return `<header class="header"><div class="header-inner">${link('/','<span class="brand-symbol">◢</span><span>A E T H E R</span>','brand')}<nav class="nav" aria-label="Main navigation">${[['/marketplace','Marketplace'],['/how-it-works','How it works'],['/network','Network'],['/docs','Docs']].map(([url,name])=>link(url,name,p===url?'active':'')).join('')}</nav><div class="header-actions">${link('/app','Launch app <span>↗</span>','button button-primary launch')}<button class="menu-toggle" aria-label="Toggle menu" aria-expanded="false">☰</button></div></div></header>`}
function footer(){return `<footer class="footer"><div class="footer-inner"><div><div class="brand foot-brand"><span class="brand-symbol">◢</span><span>A E T H E R</span></div><p>Compute without borders.</p></div><div class="footer-links">${link('/marketplace','Marketplace')}${link('/how-it-works','How it works')}${link('/network','Network')}${link('/docs','Docs')}</div><span class="footer-note">Concept product · © ${new Date().getFullYear()} Aether</span></div></footer>`}
function chart(m){return `<svg class="spark ${m.tone}" viewBox="0 0 170 36" aria-hidden="true"><polyline points="${m.points}" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function card(m){return `<article class="market-card ${m.tone}"><div class="card-heading"><div class="card-icon">${m.icon}</div><div><h3>${m.name}</h3><p>${m.subtitle}</p></div><span class="status"><i></i> Sample</span></div><div class="market-numbers"><div><strong>${m.supply}</strong><small>GPU-hours illustrated</small></div><div><strong>${m.price}</strong><small>illustrative per GPU-hour</small></div><div class="chart-wrap">${chart(m)}<small>${m.change} example</small></div></div>${link('/marketplace#'+m.id,'View market <span>→</span>','card-link')}</article>`}
function core(){return `<div class="core-wrap" aria-hidden="true"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="core-glow"></div><div class="core"><div class="core-top"></div><div class="core-face"><span class="core-logo">◢</span><span class="core-name">A E T H E R</span><span class="core-caption">COMPUTE<br>FUELS<br>PROGRESS</span></div><div class="core-side"></div></div><span class="orbit-token token-one">◢</span><span class="orbit-token token-two">◢</span></div>`}
function home(){return `<section class="hero container"><div class="hero-copy"><div class="eyebrow">THE COMPUTE EXCHANGE</div><h1>Compute, <span class="gradient-text">made liquid.</span></h1><p class="lead">Access GPU power on demand. Explore tokenized compute credits across a global network.</p><div class="hero-actions">${link('/marketplace','Explore compute <span>→</span>','button button-primary')}${link('/how-it-works','▷ &nbsp; How it works','button button-outline')}</div><div class="hero-features"><div><b>⬡</b><span>REAL UTILIZATION<small>Production-grade GPUs</small></span></div><div><b>◎</b><span>GLOBAL NETWORK<small>Distributed supply</small></span></div><div><b>◈</b><span>LIQUID MARKETS<small>Explore the concept</small></span></div></div></div>${core()}<div class="hero-side">MORE<br>COMPUTE<br>A BRIGHTER<br>TOMORROW</div></section><section class="market-section container"><div class="section-heading"><div class="eyebrow">EXPLORE THE MARKETPLACE</div><span>ILLUSTRATIVE PRICING · NO LIVE MARKETS</span></div><div class="market-grid">${markets.map(card).join('')}</div></section><div class="stats container"><div><b>◈</b><strong>42,800</strong><span>sample GPU-hours</span></div><div><b>◎</b><strong>18</strong><span>illustrative regions</span></div><div><b>◇</b><strong>99.9%</strong><span>target uptime</span></div></div>`}
function pageHero(eyebrow,title,description){return `<div class="page-hero container"><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="lead">${description}</p></div>`}
function marketplace(){return `${pageHero('MARKETPLACE','Find your next compute source.','Compare example compute products and see how a future Aether market could be structured. Values below are illustrative, not live quotes or available inventory.')}<section class="container page-section"><div class="notice"><span class="notice-dot"></span><span>Concept preview: markets, balances and prices are sample data. Trading and redemption are not enabled.</span></div><div class="market-grid">${markets.map(card).join('')}</div><div class="detail-grid">${markets.map(m=>`<article id="${m.id}" class="panel detail"><div class="eyebrow">COMPUTE PRODUCT</div><h2>${m.name}</h2><p>${m.subtitle}. A credit would represent a defined amount of eligible compute usage, subject to provider terms and verification.</p><div class="detail-row"><span>Indicative unit</span><b>1 GPU-hour</b></div><div class="detail-row"><span>Reference price</span><b>${m.price} / credit</b></div><div class="detail-row"><span>Market status</span><b>Preview only</b></div>${link('/app','Open app preview →','text-link')}</article>`).join('')}</div></section>`}
function how(){return `${pageHero('THE MODEL','From spare capacity to useful compute.','Aether is a concept for representing GPU usage rights as digital credits, with clear rules for issuing, transferring and redeeming them.')}<section class="container page-section"><div class="steps">${[['01','Source','Infrastructure providers commit eligible capacity under agreed specifications and service terms.'],['02','Verify','Capacity and performance would be checked before credits are issued against a defined GPU-hour.'],['03','Access','Users could explore available credits and connect a wallet to view the app experience.'],['04','Redeem','A future live product would exchange eligible credits for scheduled compute, with usage and settlement records.']].map(([n,t,d])=>`<div class="step"><span>${n}</span><div><h2>${t}</h2><p>${d}</p></div></div>`).join('')}</div><div class="split-panel"><div><div class="eyebrow">BUILT FOR CLARITY</div><h2>One credit. A defined unit of compute.</h2><p>Token rules need to state the hardware class, duration, region, availability window and redemption rights. These terms are product requirements for a future implementation.</p></div>${link('/docs','Read product docs →','button button-outline')}</div></section>`}
function network(){return `${pageHero('THE NETWORK','Compute without borders.','A proposed network that connects infrastructure providers and builders through transparent compute products.')}<section class="container page-section"><div class="network-grid"><article class="panel"><span class="large-icon">◎</span><h2>For providers</h2><p>Publish capacity with defined hardware specifications, regions, schedules and service terms.</p></article><article class="panel"><span class="large-icon">⬡</span><h2>For builders</h2><p>Compare compute products, understand credit terms and choose capacity suited to a workload.</p></article><article class="panel"><span class="large-icon">◇</span><h2>For the network</h2><p>Make utilization, credit issuance and redemption auditable before activating real markets.</p></article></div><div class="network-visual"><div class="eyebrow">NETWORK ARCHITECTURE · CONCEPT</div><div class="flow"><span>PROVIDERS</span><i>→</i><span>VERIFIED CAPACITY</span><i>→</i><span>COMPUTE CREDITS</span><i>→</i><span>BUILDERS</span></div><p>No providers or regions are connected in this preview.</p></div></section>`}
function docs(){return `${pageHero('DOCUMENTATION','The building blocks.','An overview of the proposed product model and the boundaries of this frontend preview.')}<section class="container page-section docs-layout"><aside class="docs-nav"><a href="#overview">Overview</a><a href="#credits">Compute credits</a><a href="#wallet">Wallet connection</a><a href="#status">Current status</a></aside><div class="docs-content"><article id="overview"><div class="eyebrow">01 / OVERVIEW</div><h2>What is Aether?</h2><p>Aether is a frontend concept for a marketplace of tokenized AI compute. It shows how users might discover compute products and connect an EVM wallet. It does not execute trades, issue tokens or provision GPUs.</p></article><article id="credits"><div class="eyebrow">02 / PRODUCT MODEL</div><h2>What a compute credit would mean</h2><p>A production credit would need published redemption terms: GPU type, duration, provider, region, performance requirements, scheduling, expiry, and remedies if capacity is unavailable. The examples shown here are placeholders.</p></article><article id="wallet"><div class="eyebrow">03 / WALLET</div><h2>Connecting a wallet</h2><p>The app asks an injected EVM wallet for account access using the standard <code>eth_requestAccounts</code> method. It displays the selected address and responds to account or chain changes. Connecting does not request a signature or transaction.</p></article><article id="status"><div class="eyebrow">04 / STATUS</div><h2>Preview limitations</h2><p>All displayed quantities, reference prices, changes and network metrics are sample data. There are no smart contracts, payments, live orders, real balances or GPU provisioning in this release.</p></article></div></section>`}
function app(){return `${pageHero('AETHER APP','Compute dashboard.','Connect an EVM wallet to see your address. Browse example markets while the product infrastructure is being developed.')}<section class="container page-section"><div class="app-grid"><div class="panel wallet-panel"><div class="eyebrow">WALLET</div><h2 id="wallet-title">${state.wallet?'Wallet connected':'Connect to get started'}</h2><p id="wallet-description">${state.wallet?'Your wallet is connected to this browser session. No balances are loaded.':'Use an installed EVM wallet such as MetaMask or another compatible browser wallet.'}</p><div class="wallet-address" id="wallet-address">${state.wallet||'No wallet connected'}</div><div class="wallet-actions"><button class="button button-primary" id="connect-wallet">${walletLabel()}</button>${state.wallet?'<button class="button button-outline" id="disconnect-wallet">Disconnect</button>':''}</div><p class="wallet-message" role="status" id="wallet-message"></p></div><div class="panel account-panel"><div class="eyebrow">YOUR OVERVIEW</div><div class="account-row"><span>Available credits</span><strong>—</strong></div><div class="account-row"><span>Active reservations</span><strong>—</strong></div><div class="account-row"><span>Network</span><strong id="chain-name">${chainName()}</strong></div><div class="notice compact">Balances and reservations require a live backend and contracts.</div></div></div><div class="section-heading app-heading"><div class="eyebrow">EXPLORE COMPUTE</div><span>PREVIEW DATA</span></div><div class="market-grid">${markets.map(card).join('')}</div></section>`}
function chainName(){return window.ethereum?.chainId ? `Chain ID ${parseInt(window.ethereum.chainId,16)}` : 'Not connected'}
function render(){let p=route();let content=({'/':home,'/marketplace':marketplace,'/how-it-works':how,'/network':network,'/docs':docs,'/app':app})[p];document.querySelector('#app').innerHTML=header()+`<main>${content?content():`<section class="page-hero container"><div class="eyebrow">404</div><h1>Page not found.</h1>${link('/','Return home →','button button-primary')}</section>`}</main>`+footer();bind();}
function bind(){document.querySelector('.menu-toggle')?.addEventListener('click',e=>{let open=document.querySelector('.nav').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});document.querySelector('#connect-wallet')?.addEventListener('click',connect);document.querySelector('#disconnect-wallet')?.addEventListener('click',()=>{state.wallet=null;render();message('Disconnected from this page. Your wallet extension may retain its site permission.')});}
function message(msg){let el=document.querySelector('#wallet-message');if(el)el.textContent=msg}
async function connect(){if(state.connecting)return;if(!window.ethereum?.request){message('No EVM wallet detected. Install a compatible browser wallet and try again.');return}state.connecting=true;let button=document.querySelector('#connect-wallet');button.disabled=true;button.textContent='Connecting…';try{let accounts=await window.ethereum.request({method:'eth_requestAccounts'});if(accounts?.[0]){state.wallet=accounts[0];render();message('Wallet connected. No transaction or signature was requested.')}else message('No account was selected.')}catch(error){message(error.code===4001?'Connection was declined.':`Could not connect wallet: ${error.message||'unknown error'}`)}finally{state.connecting=false;let btn=document.querySelector('#connect-wallet');if(btn)btn.disabled=false}}
if(window.ethereum?.on){window.ethereum.on('accountsChanged',accounts=>{state.wallet=accounts?.[0]||null;if(route()==='/app'){render();message(state.wallet?'Wallet account changed.':'Wallet disconnected.')}});window.ethereum.on('chainChanged',()=>{if(route()==='/app')render()})}
render();
